{{- if not .Values.mapping.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sure-networth.fullname" . }}
  labels:
    {{- include "sure-networth.labels" . | nindent 4 }}
data:
  mapping.json: |
    {{- dict "accounts" .Values.mapping.accounts "netting" .Values.mapping.netting | toPrettyJson | nindent 4 }}
{{- end }}
